import type { TLang } from "@/utils/types";

export const ua: TLang = {
  code: "Перегляд коду",
  schools: {
    cat: "Кота",
    wolf: "Вовка",
    griffin: "Грифона",
    bear: "Ведмідя",
    forgotten_wolf: "Забутий Вовк",
    viper: "Змії",
    manticore: "Мантикори",
  },
  gears: {
    armor: "Броня",
    boots: "Чоботи",
    gauntlets: "Рукавички",
    trousers: "Штанці",
    silverSword: "Меч сріблястий",
    steelSword: "Меч сталевий",
    crossbow: "Арбалет",
  },
  level: "рів.",
  levels: {
    basic: "Базова",
    enhanced: "Покращена",
    superior: "Відмінна",
    mastercrafted: "Мейстерські",
    grandmaster: "Гросмейстерська",
  },
  popup: {
    title: "Пошук був вдалим?",
    crafted: "Виготовлено, лежить в торбині",
    equipped: "Знайдено креслення",
    default: "Досі нічого",
  },
  stonesLevel: ["", "", "Малий", "Стандартний", "Великий"],
  stones: {
    Dazhdbog: "Даждьбог",
    Chernobog: "Чернобог",
    Devana: "Девана",
    Morana: "Марена",
    Perun: "Перун",
    Svarog: "Сварог",
    Stribog: "Стрибог",
    Triglav: "Триглав",
    Veles: "Велес",
    Zoria: "Зоря",
    Pie: "Пиріг",
    Curd: "Творог",
    Yrden: "Ірдена",
    Quen: "Квена",
    Igni: "Ігні",
    Axii: "Аксія",
    Aard: "Аарда",
    Binding: "Зв'язуючий",
    Mending: "Покращенний",
    Reinforcement: "Армування",
    Warding: "Охорона",
  },
};

export const en: TLang = {
  code: "Code review",
  schools: {
    cat: "Cat",
    wolf: "Wolf",
    griffin: "Griffin",
    bear: "Bear",
    forgotten_wolf: "Forgotten Wolven",
    viper: "Viper",
    manticore: "Manticore",
  },
  gears: {
    armor: "Armor",
    boots: "Boots",
    gauntlets: "Gauntlets",
    trousers: "Trousers",
    silverSword: "Sword Silver",
    steelSword: "Sword Steel",
    crossbow: "Crossbow",
  },
  level: "lvl.",
  levels: {
    basic: "Feline",
    enhanced: "Enhanced",
    superior: "Superior",
    mastercrafted: "Mastercrafted",
    grandmaster: "Grandmaster",
  },
  popup: {
    title: "Did You find something?",
    crafted: "Finelly crafted",
    equipped: "Found some paper",
    default: "Still nothing",
  },
  stonesLevel: ["", "", "Little", "Default", "Large"],
  stones: {
    Dazhdbog: "Dazhdbog",
    Chernobog: "Chernobog",
    Devana: "Devana",
    Morana: "Morana",
    Perun: "Perun",
    Svarog: "Svarog",
    Stribog: "Stribog",
    Triglav: "Triglav",
    Veles: "Veles",
    Zoria: "Zoria",
    Pie: "Pie",
    Curd: "Curd",
    Yrden: "Yrden",
    Quen: "Quen",
    Igni: "Igni",
    Axii: "Axii",
    Aard: "Aard",
    Binding: "Binding",
    Mending: "Mending",
    Reinforcement: "Reinforcement",
    Warding: "Warding",
  },
};
